// skillIcons.js
import * as Icons from '../Icons';

export const skillIcons = {
  JavaScript: Icons.Javascript,
  TypeScript: Icons.Typescript,
  HTML: Icons.Html5,
  CSS: Icons.Css,
  Angular: Icons.Angular,
  'Angular 10+': Icons.Angular,
  'Angular 15': Icons.Angular,
  'Angular 4': Icons.Angular,
  'React.js': Icons.React,
  'Redux-Saga': Icons.Reduxsaga,
  Cypress: Icons.Cypress,
  JSON: Icons.Json,
  Git: Icons.Github,
  Jira: Icons.Jira,
  Docker: Icons.Docker,
  Sass: Icons.Sass,
  Webpack: Icons.Webpack,
  'styled-components': Icons.Styledcomponents,
  'GitHub Actions': Icons.Githubactions,
  MongoDB: Icons.Mongodb,
  'Node.js': Icons.Nodedotjs,
  Tailwind: Icons.Tailwindcss,
  Axios: Icons.Axios,
  Chai: Icons.Chai,
  'Amazon EC2': Icons.Amazonec2,
  'Vanilla JS (ES5, ES6)': Icons.Javascript,
  React: Icons.React,
  LinkedIn: Icons.Icons8Linkedin,
  GitHub: Icons.Github,
  HTML5: Icons.Html5,
  CSS3: Icons.Css,
};
